### ISSUE TITLE
username != null

### ISSUE THREAD

**Issue by cburk2019** [Chat-LI/Chat-Li-Backend#39]
When a client enters into the app in their terminal, before account creation, their username is displayed as 'null'
Testing
-> user1 opens app
	-> user1 logs in
-> user2 opens app

-> before user2 chooses options 1 or 2
	-> user1 runs /listUsers

(user2 shows as null)

-> user2 registers/login

(user2 shows as [username])

**Comment by KasonBraley** [comment]
Fixed #40
